### ISSUE TITLE
TypeError: Cannot read property 'info' of undefined

### ISSUE THREAD

**Issue by jacargentina** [fergiemcdowall/search-index-adder#8]
I'm getting this when finishing an indexing

```
/home/.../node_modules/search-index/lib/siUtil.js:33
       siOptions.log.info('closed...')
                    ^

TypeError: Cannot read property 'info' of undefined
    at /home/.../node_modules/search-index/lib/siUtil.js:33:21
    at /home/.../node_modules/levelup/lib/levelup.js:141:18
    at /home/.../node_modules/abstract-leveldown/abstract-leveldown.js:65:7

```

**Comment by jacargentina** [comment]
Sorry, wrong project
